In [1]:
import cv2
import numpy as np

##  CREATING A BLANK WHITE CANVAS - BOŞ BEYAZ BİR TUVAL OLUŞTURMA

In [2]:
canvas = np.ones((400, 400, 3), dtype="uint8") * 255

## DRAWING A CIRCLE ON THE CANVAS - TUVALE DAİRE ÇİZME

In [3]:
cv2.circle(canvas, (200, 200), 50, (0, 0, 255), 3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## DRAWING A RECTANGLE ON THE CANVAS - TUVALE DİKDÖRTGEN ÇİZME

In [4]:
cv2.rectangle(canvas, (50, 50), (150, 150), (255, 0, 0), 2)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## DRAWING LINES ON THE CANVAS - TUVALE ÇİZGİ ÇİZME

In [5]:
cv2.line(canvas, (300, 50), (350, 100), (0, 255, 0), 4)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## DRAWING AN ELLIPSE ON THE CANVAS - TUVALE ELİPS ÇİZME

In [6]:
cv2.ellipse(canvas, (300, 300), (80, 40), 0, 0, 360, (255, 0, 255), 3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## CREATING POLYGONS (PENTAGON SHAPE) - POLİGON OLUŞTURMA (BEŞGEN ŞEKLİ)

In [7]:
points = np.array([[200, 50], [250, 100], [225, 150], [175, 150], [150, 100]], np.int32)
points = points.reshape((-1, 1, 2))
cv2.polylines(canvas, [points], True, (0, 255, 255), 2)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

## PROCESS OF SHOWING THE CANVAS - TUVALİ GÖSTERME İŞLEMİ

In [8]:
cv2.imshow("Shapes", canvas)

while True:
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cv2.destroyAllWindows()

## IDENTIFYING SHAPES IN IMAGES - GÖRSELDEKİ ŞEKİLLERİ BELİRLEME

In [9]:
image = cv2.imread("C:\\Users\\Sena\\Downloads\\gorsel.jpeg") 

In [10]:
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.imshow("image", image)
cv2.waitKey(0)

-1

In [11]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.namedWindow("gray",cv2.WINDOW_NORMAL)
cv2.imshow("gray",gray)
cv2.waitKey(0)

-1

## DETECTING EDGES - KENARLARI TESPİT ETME

In [12]:
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

edges = cv2.Canny(blurred, 50, 150)
cv2.namedWindow("blurred",cv2.WINDOW_NORMAL)
cv2.imshow("blurred", edges)
cv2.waitKey(0)

-1

## FINDING CONTOURS - KONTURLARI BULMA

In [13]:
contours, _ = cv2.findContours(edges, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

In [14]:
for contour in contours:
    perimeter = cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, 0.04 * perimeter, True)

    M = cv2.moments(contour)
    if M['m00'] != 0:
        cx = int(M['m10'] / M['m00'])
        cy = int(M['m01'] / M['m00'])
    else:
        cx, cy = 0, 0

    if len(approx) == 3:
        shapeName = "Triangle"
    elif len(approx) == 4:
        (x, y, w, h) = cv2.boundingRect(approx)
        aspectRatio = float(w) / h
        shapeName = "Square" if 0.95 <= aspectRatio <= 1.05 else "Rectangle"
    elif len(approx) > 4:
        shapeName = "Circle"
    else:
        shapeName = "Unknown"

    cv2.drawContours(image, [approx], -1, (0, 255, 0), 3)
    cv2.putText(image, shapeName, (cx - 50, cy - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)

cv2.namedWindow("Shape Detection",cv2.WINDOW_NORMAL)
cv2.imshow("Shape Detection", image)
cv2.waitKey(0)
cv2.destroyAllWindows()